- front/src/components/logIn.js
- front/src/components/login/enter.js
- front/src/components/login/logIn.js
- front/src/components/login/recovery.js
- front/src/components/login/register.js
- front/src/components/styles.module.css
- front/src/components/welcome.js
Componente general que incluye:
- Pantalla de Login con MAIL y CONTRASEÑA
- Pantalla de Registro con NOMBRE, APELLIDO, MAIL Y CONTRASEÑA
- Pantalla de Recuperar contraseña con MAIL
> Pantalla de login

- backend/env.example
- backend/index.js
- backend/package-lock.json
- backend/package.json
instaladas dependencias requeridas, agregado codigo boilerplate para el backend.
-express
-mongoose
-dotenv
-nodemon
el script npm start = nodemon index.js
> boilerplate

- backend/index.js
- backend/models/Product.js
- backend/routes/products.js
En este commit:
- schema de Producto para la BD
- rutas CRUD para Productos: Buscar todos, Buscar uno, agregar un producto, borrar un producto, editar un producto.
favor echar un ojo y comentarme si hay algo que debo cambiar.
> add Product schema, add basic product CRUD routes for Products

- front/package.json
- front/src/App.js
- front/src/app/store.js
- front/src/components/login/enter.js
- front/src/components/login/logIn.js
- front/src/components/products.js
- front/src/components/products/MOCK_DATA.json
- front/src/components/products/editProduct.js
- front/src/components/products/listaProductos.js
- front/src/components/products/products.js
- front/src/components/session/session.js
- front/src/components/styles.module.css
- front/src/components/welcome.js
- front/src/features/userSlices.js
- front/src/index.js
- front/yarn.lock
Se creó la página de productos con las funcionalidades correspondientes (editar, borrar y ver)
> Products screen

- backend/models/Admin.js
- backend/routes/admin.route.js
en este commit 
- compare pasword method
- login method
- post route for admin login
> add admin schema method for compare password and and login as well as the post route

- backend/models/Sale.js
- backend/routes/SalesRoutes.js
en este commit:
- schema para ventas
- routes para ventas
> add schema for sales as well as the routes

- backend/routes/adminsRoutes.js
los cambios hechos durante la llamada de hoy
> changed create admin route from controller to adminsRoutes

- backend/models/Admin.js
- backend/models/Sale.js
- backend/routes/SalesRoutes.js
in this commit:
-some housekeeping
-statistics route for sales
> removed commented code and implemented route for sale statistics

- front/README.md
- front/package.json
- front/src/components/login/recovery/recovery.js
- front/src/components/sales/newSale/sale.js
- front/src/components/sales/newSale/saleDetails.js
- front/src/components/sales/oldSales/ListOldSales.js
- front/src/components/sales/oldSales/oldSales.js
- front/src/components/stats/statsIndex.js
- front/src/components/stats/statsInputs.js
- front/yarn.lock
Stats VISUAL complete and working properly
Domain set based on .env files
> Stats and domain changes

- backend/models/Sale.js
-rewrote sales model
-now takes a product object with name, price and quantity
> modified sales model, now it doesnt relate to products table

- backend/models/Admin.js
- backend/package-lock.json
- backend/package.json
- backend/routes/adminsRoutes.js
- backend/yarn.lock
-added nodemailer package
-added Admin model method to send an email with password recovery instructions
-implemented the model method in a route called /admin/forgot-password
> added nodemailer to send forgot password email

- front/README.md
- front/src/App.js
- front/src/components/login/changePass/changePassForm.js
- front/src/components/login/recovery/recovery.js
- front/src/components/pagination/paginationList.js
- front/src/components/pagination/paginationSelect.js
- front/src/components/products/listaProductos.js
- front/src/components/products/products.js
- front/src/components/products/productsBar.js
- front/src/components/sales/newSale/productSearch.js
- front/src/components/sales/newSale/sale.js
- front/src/components/sales/newSale/saleDetails.js
- front/src/components/sales/newSale/saleQuantity.js
- front/src/components/sales/oldSales/ListOldSales.js
- front/src/components/styles.module.css
- front/src/pages/changePass.js
- Create New Password VISUAL created
- From link route created
- Product VISUALS corrected
- Create PAGINATION component
- Add PAGINATION to product VISUAL
- Fixed PRODUCTS loading from Backend bug
> Recovery and Products VISUALS

- backend/routes/SalesRoutes.js
- backend/seeders/sales-data.json
- backend/seeders/sales-seeder.js
- seeder file for sales
- fixed post route for single sale
> seeder file for sales and fixed create sales route

- backend/models/Admin.js
- backend/seeders/sales-data.json
- backend/seeders/sales-seeder.js
- reset password method now works properly
- new sales seeded into db
> fixed password reset route, eliminated all sales and injected 14 new ones

- backend/index.js
- backend/middleware/getCounter.js
- backend/models/Category.js
- backend/models/Counter.js
- backend/models/Product.js
- backend/models/Sale.js
- backend/routes/SalesRoutes.js
- backend/routes/categoriesRoutes.js
- backend/routes/counterRoutes.js
- backend/routes/productsRoutes.js
in this commit:
- counter model and routes
- category model and routes
- added counter functionality to sales and products as well in categories
> added counter functionality and category model

- front/README.md
- front/src/components/login/enter.js
- front/src/components/login/enterForm.js
- front/src/components/login/logIn.js
- front/src/components/styles.module.css
All CSS for LOGIN VISUAL
REMEMBER ME implementation:
* Save on Local Storage the information of email and password. DONE
- Add a new key on the USERDATA state. DONE
* Create REMEMBER ME checkbox. DONE
* Recover the REMEMBERED data from local storage if it exist. DONE.
> Login css / new checkbox

- front/README.md
- front/public/cancel.svg
- front/src/components/pagination/paginationSales.js
- front/src/components/sales/oldSales/oldSales.js
- front/src/components/styles.module.css
* Delete the EDIT SALES button. DONE.
* Add CHECKALL checkbox in the SaleBar component. DONE.
* Check all and uncheck all when clicking on CHECKALL box. DONE.
* ISSUE: When navigating on PAGINATION and it loads less than eight elements, the extra elements from previous pages just uncheck. SOLVED with a defaultChecked attribute.
* Create the STATE buttons. DONE.
* Create de CANCEL action button. DONE.
- Create the Modal to confirm and explain why. IN PROCESS.
- Reload page when some state changes. DONE.
> Sale cancel function

- front/src/components/BarChart/BarChart.css
- front/src/components/BarChart/BarChart.js
- front/src/components/NavBar/NavBar.css
- front/src/components/NavBar/NavBar.js
- front/src/components/Welcome/Welcome.css
- front/src/components/login/logIn.js
- graphs are now inside a card
- navbar dropdown menu now closes when clicked outside
- login error now displayed inside login form
> styling for graphs and other minor fixes

- front/README.md
- front/src/Images/icons/showSale.svg
- front/src/components/pagination/paginationList.js
- front/src/components/pagination/paginationSales.js
- front/src/components/sales/newSale/sale.js
- front/src/components/sales/newSale/saleBar.js
- front/src/components/sales/oldSales/ListOldSales.js
- front/src/components/sales/oldSales/oldSales.js
- front/src/components/sales/oldSales/showSale.js
- front/src/components/styles.module.css
* I need a modal to show the sales information. DONE.
* IMPORTANT: Change SALESBAR to recieve an array instead of individual column names. DONE.
* Working on modal. DONE.
CSS
- Add background blur. DONE
- Need "go back" button. DONE.
- Need to see "Total Sale". DONE.
- ADD pay method. DONE.
- ADD Sale state. DONE.
- ADD sale number. DONE.
> Sale show complete

- front/README.md
- front/src/components/pagination/paginationSelect.js
- front/src/components/styles.module.css
- front/yarn.lock
* Not to resize when changing pages. DONE.
> pagination resize

- front/README.md
- front/src/components/login/logIn.js
- front/src/components/products/listaProductos.js
- front/src/components/products/products.js
- front/src/components/products/productsBar.js
- front/src/components/sales/newSale/productSearch.js
- front/src/components/sales/newSale/saleBar.js
- front/src/components/styles.module.css
- front/src/components/upperBar.js/upperBar.js
Products visual is loading well. 
- The post and patch calls must be reviewed.
> Products loading fine

- front/README.md
- front/src/components/pagination/paginationProducts.js
- front/src/components/products/categorias.js
- front/src/components/products/editProduct.js
- front/src/components/products/listaProductos.js
- front/src/components/products/products.js
- front/src/components/styles.module.css
* Create categories component. DONE.
* Add the delete functionality. DONE.
* Styling delete button. DONE.
> Categories functional

- front/README.md
- front/src/components/pagination/paginationList.js
- front/src/components/pagination/paginationProducts.js
- front/src/components/products/categorias.js
- front/src/components/products/editProduct.js
- front/src/components/products/listaProductos.js
- front/src/components/products/products.js
- front/src/components/styles.module.css
* On products: Action buttons needs GAP. DONE.
* General window change size when there are few products. DONE.
* Show deactivated products with low opacity. DONE. (it seems to work but would be nice if we check it!)
* Delete category error message. DONE.
> New corrections

- front/src/components/BarChart/BarChart.css
- front/src/components/BarChart/BarChart.js
- front/src/components/NavBar/NavBar.css
- front/src/components/NavBar/NavBar.js
- front/src/components/UserProfileModal/UserProfileModal.js
- front/src/components/Welcome/Welcome.css
- front/src/components/Welcome/welcome.js
- front/src/components/styles.module.css
- front/src/pages/welcomePage.js
-index page properly aligned
-link cards for products and sales now properly change the active state for the navbar
-eye icon in login now has a media query for its position. position is now measured in %.
> css ux/ui changes
